# Generated by Django 4.2 on 2023-05-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
