# Generated by Django 4.2 on 2023-05-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='places.place')),
                ('emo_text', models.TextField(verbose_name='emotion_text')),
                ('is_liked', models.BooleanField(default=False)),
                ('visit_date', models.DateField()),
            ],
        ),
    ]
