# Generated by Django 4.2 on 2023-06-06 13:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_note_emo_text_alter_place_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7bc67b8b-7aff-4904-be43-fdc829d05fbd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
