# Generated by Django 4.2 on 2023-06-06 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.UUIDField(default=uuid.UUID('72425b49-6f52-4f31-9f64-337b6b7e6e5e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
